### ISSUE TITLE
Install from github causes error

### ISSUE THREAD

**Issue by dagda1** [mdespuits/dotify#21]
I have tried to install my dofiles from an existing github repo.

I installed via the following command

```
dotify github dagda1/dots
```

If I run a command such as 

```
dotify list
```

I get the following error:

> ➜  ~  dotify list
> /Users/paulcowan/.rvm/rubies/ruby-1.9.3-preview1/lib/ruby/1.9.1/psych.rb:154:in `parse': (/Users/paulcowan/.dotrc): couldn't parse YAML at line 8 column 8 (Psych::SyntaxError)
>         from /Users/paulcowan/.rvm/rubies/ruby-1.9.3-preview1/lib/ruby/1.9.1/psych.rb:154:in`parse_stream'
>         from /Users/paulcowan/.rvm/rubies/ruby-1.9.3-preview1/lib/ruby/1.9.1/psych.rb:125:in `parse'
>         from /Users/paulcowan/.rvm/rubies/ruby-1.9.3-preview1/lib/ruby/1.9.1/psych.rb:112:in`load'
>         from /Users/paulcowan/.rvm/rubies/ruby-1.9.3-preview1/lib/ruby/1.9.1/psych.rb:229:in `load_file'
>         from /Users/paulcowan/.rvm/gems/ruby-1.9.3-preview1/gems/dotify-0.6.6/lib/dotify/config.rb:49:in`retrieve'
>         from /Users/paulcowan/.rvm/gems/ruby-1.9.3-preview1/gems/dotify-0.6.6/lib/dotify/config.rb:43:in `ignore'
>         from /Users/paulcowan/.rvm/gems/ruby-1.9.3-preview1/gems/dotify-0.6.6/lib/dotify/filter.rb:26:in`filter_ignore_files!'
>         from /Users/paulcowan/.rvm/gems/ruby-1.9.3-preview1/gems/dotify-0.6.6/lib/dotify/filter.rb:9:in `home'
>         from /Users/paulcowan/.rvm/gems/ruby-1.9.3-preview1/gems/dotify-0.6.6/lib/dotify/collection.rb:12:in`initialize'
>         from /Users/paulcowan/.rvm/gems/ruby-1.9.3-preview1/gems/dotify-0.6.6/lib/dotify.rb:23:in `new'
>         from /Users/paulcowan/.rvm/gems/ruby-1.9.3-preview1/gems/dotify-0.6.6/lib/dotify.rb:23:in`collection'
>         from /Users/paulcowan/.rvm/gems/ruby-1.9.3-preview1/gems/dotify-0.6.6/lib/dotify/cli.rb:88:in `list'
>         from /Users/paulcowan/.rvm/gems/ruby-1.9.3-preview1/gems/thor-0.15.4/lib/thor/task.rb:27:in`run'
>         from /Users/paulcowan/.rvm/gems/ruby-1.9.3-preview1/gems/thor-0.15.4/lib/thor/invocation.rb:120:in `invoke_task'
>         from /Users/paulcowan/.rvm/gems/ruby-1.9.3-preview1/gems/thor-0.15.4/lib/thor.rb:275:in`dispatch'
>         from /Users/paulcowan/.rvm/gems/ruby-1.9.3-preview1/gems/thor-0.15.4/lib/thor/base.rb:425:in `start'
>         from /Users/paulcowan/.rvm/gems/ruby-1.9.3-preview1/gems/dotify-0.6.6/bin/dotify:6:in`<top (required)>'
>         from /Users/paulcowan/.rvm/gems/ruby-1.9.3-preview1/bin/dotify:19:in `load'
>         from /Users/paulcowan/.rvm/gems/ruby-1.9.3-preview1/bin/dotify:19:in`<main>'

My .dotrc looks like this

```
# Set the editor to use when editing Dotify dotfiles.
#   Default: 'vim'
#   Options: 'vi', 'vim', 'emacs', '[ANY OTHER TERMINAL BASED EDITOR]'
#
  editor: 'vi'
#
# Ignoring files in ~/.dotify when linking:
#
 ignore:
   dotify:
   - '.git'
   - '.gitignore'
   - '.gitmodules'
   # Ignoring files in the home directory when linking:
   dotify:
   - '.rbenv'
   - '.rvm'
```
